# Generated by Django 5.2.14 on 2026-07-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="share_scope",
            field=models.CharField(
                choices=[("local", "This community only"), ("federated", "Discoverable by linked communities")],
                default="local",
                max_length=10,
            ),
        ),
    ]
