# Generated by Django 5.2.14 on 2026-07-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offers", "0002_offer_share_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="moderation_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
