# Generated by Django 5.2.14 on 2026-08-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_email_notifications_optout"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="verified_via",
            field=models.CharField(
                blank=True,
                choices=[
                    ("email", "Email link"),
                    ("coordinator", "Coordinator vouch"),
                    ("backfill", "Pre-gate account"),
                ],
                default="",
                max_length=12,
            ),
        ),
    ]
