# Generated by Django 5.2.14 on 2026-09-27 03:19

"""Email ownership, separate from human verification (docs/specs/email-confirmation.md, #172).

NO data migration, deliberately. NULL for every existing row is the correct value: in
production on 2026-09-26 no real account had ever clicked a confirmation link, so marking
any address as proven would record something that never happened. The spec refuses
grandfathering by name — it would make the exposure it measured permanent.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_backfill_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
