# Generated by Django 5.2.14 on 2026-09-29 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_email_confirmed_at"),
        ("communities", "0003_member_removed_at_member_removed_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecoveryCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("recovery_code", "Printed recovery code"),
                            ("coordinator_reset", "Coordinator-issued reset"),
                            ("admin_unlock", "Admin unlock"),
                            ("claim", "Account claim link"),
                        ],
                        max_length=20,
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("issued_by_label", models.CharField(blank=True, default="", max_length=150)),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="communities.member",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recovery_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_recovery_credential",
                "indexes": [models.Index(fields=["user", "purpose"], name="recovery_cred_user_purpose")],
            },
        ),
    ]
