# Generated by Django 5.2.14 on 2026-09-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_recovery_credential"),
    ]

    operations = [
        migrations.AddField(
            model_name="recoverycredential",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
