# Generated by Django 5.2.14 on 2026-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_recovery_credential_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoSignupCount",
            fields=[
                ("country", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("count", models.PositiveIntegerField(default=0)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accounts_geo_signup_count",
                "ordering": ["-count"],
            },
        ),
    ]
