# Generated by Django 5.2.14 on 2026-10-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_geo_signup_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
