# Generated by Django 5.2.14 on 2026-06-21 01:23

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.state


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("slug", models.SlugField()),
                ("label", models.CharField(max_length=80)),
                ("icon", models.CharField(blank=True, default="", max_length=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("authority", "Authority"),
                            ("ministry", "Ministry"),
                            ("professional", "Professional"),
                            ("life_status", "Life Status"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("self_serve", "Self-serve (no verification needed)"),
                            ("coordinator_verified", "Coordinator or Admin verifies"),
                            ("admin_verified", "Admin only verifies"),
                        ],
                        default="self_serve",
                        max_length=25,
                    ),
                ),
                (
                    "public_when_verified",
                    models.BooleanField(
                        default=False, help_text="If True, this tag is visible to ALL community members when verified."
                    ),
                ),
                (
                    "default_visibility",
                    models.CharField(
                        choices=[
                            ("public", "All community members"),
                            ("community", "Community members"),
                            ("coordinators_only", "Coordinators only"),
                        ],
                        default="community",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tags", to="communities.community"
                    ),
                ),
            ],
            options={
                "db_table": "tags_tag",
                "ordering": ["sort_order", "label"],
                "unique_together": {("community", "slug")},
            },
        ),
        migrations.CreateModel(
            name="MemberTag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("self_claimed", "Self-claimed"),
                            ("pending", "Pending verification"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("revoked", "Revoked"),
                            ("removed", "Removed"),
                        ],
                        default="self_claimed",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "All community members"),
                            ("community", "Community members"),
                            ("coordinators_only", "Coordinators only"),
                        ],
                        default="community",
                        help_text="Member's chosen visibility (cannot exceed tag's default).",
                        max_length=20,
                    ),
                ),
                (
                    "evidence_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Justification for verification (no PII — e.g. 'confirmed at ordination 2019').",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("rejection_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="member_tags", to="communities.member"
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags_revoked",
                        to="communities.member",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags_verified",
                        to="communities.member",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="tags.tag"
                    ),
                ),
            ],
            options={
                "db_table": "tags_member_tag",
                "indexes": [
                    models.Index(fields=["tag", "status"], name="tags_mt_tag_status_idx"),
                    models.Index(fields=["member", "status"], name="tags_mt_member_status_idx"),
                ],
                "unique_together": {("member", "tag")},
            },
            bases=(apps.common.state.StateMachineMixin, models.Model),
        ),
    ]
