# §12.3 name blind index, Stage A — ADDITIVE ONLY (new nullable column + index;
# no data touched). Existing rows keep name_bidx NULL until the separate, gated
# Stage C backfill runs; `manage.py person_bidx_status` reports the gap.
# Generated by Django 5.2.16 on 2026-07-14 15:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0002_resource_directory"),
        ("households", "0001_initial"),
        ("people", "0003_person_envelope_backfill"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="name_bidx",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["name_bidx"], name="people_person_name_bidx"),
        ),
    ]
