# Generated by Django 5.2.14 on 2026-10-01 19:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("casework", "0008_case_sensitivity_default_restricted"),
        ("communities", "0004_member_role_intake"),
        ("needs", "0006_contact_pref_default_any"),
        ("people", "0004_person_name_bidx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalHold",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all", "Everything (every automated deletion stops)"),
                            ("community", "One community: its cases and needs"),
                            ("person", "One person: every case about them"),
                            ("case", "One case"),
                            ("need", "One need"),
                        ],
                        max_length=12,
                    ),
                ),
                ("reference", models.CharField(max_length=200)),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="casework.casefile"
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="communities.community"
                    ),
                ),
                (
                    "need",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="needs.need"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="people.person"
                    ),
                ),
                (
                    "placed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "released_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "holds_legal_hold",
                "ordering": ["-placed_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("case__isnull", True),
                                ("community__isnull", True),
                                ("need__isnull", True),
                                ("person__isnull", True),
                                ("scope", "all"),
                            ),
                            models.Q(
                                ("case__isnull", True),
                                ("community__isnull", False),
                                ("need__isnull", True),
                                ("person__isnull", True),
                                ("scope", "community"),
                            ),
                            models.Q(
                                ("case__isnull", True),
                                ("community__isnull", True),
                                ("need__isnull", True),
                                ("person__isnull", False),
                                ("scope", "person"),
                            ),
                            models.Q(
                                ("case__isnull", False),
                                ("community__isnull", True),
                                ("need__isnull", True),
                                ("person__isnull", True),
                                ("scope", "case"),
                            ),
                            models.Q(
                                ("case__isnull", True),
                                ("community__isnull", True),
                                ("need__isnull", False),
                                ("person__isnull", True),
                                ("scope", "need"),
                            ),
                            _connector="OR",
                        ),
                        name="legal_hold_target_matches_scope",
                    )
                ],
            },
        ),
    ]
