# Generated by Django 5.2.14 on 2026-07-12 06:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flag",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "target_type",
                    models.CharField(
                        choices=[("need", "Need"), ("offer", "Offer"), ("member", "Member")], max_length=12
                    ),
                ),
                ("target_id", models.UUIDField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("fake", "Seems fake or misleading"),
                            ("unsafe", "Unsafe or threatening"),
                            ("spam", "Spam or off-topic"),
                            ("other", "Something else"),
                        ],
                        max_length=12,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved"), ("dismissed", "Dismissed")],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="flags", to="communities.community"
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flags_raised",
                        to="communities.member",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flags_resolved",
                        to="communities.member",
                    ),
                ),
            ],
            options={
                "db_table": "moderation_flag",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["community", "status"], name="mod_flag_comm_status_idx"),
                    models.Index(fields=["target_type", "target_id"], name="mod_flag_target_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "open")),
                        fields=("reporter", "target_type", "target_id"),
                        name="mod_flag_one_open_per_reporter",
                    )
                ],
            },
        ),
    ]
