# Generated by Django 5.2.16 on 2026-07-12 01:24

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.state


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communities", "0001_initial"),
        ("needs", "0004_need_share_scope"),
        ("offers", "0002_offer_share_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("fake_or_scam", "Fake or scam"),
                            ("inappropriate", "Inappropriate content"),
                            ("safety", "Safety concern"),
                            ("spam", "Spam or duplicate"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional context for coordinators. Please don't include personal details.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("content_hidden", "Content hidden"),
                            ("no_action", "Reviewed — no action needed"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="communities.community",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags_received",
                        to="communities.member",
                    ),
                ),
                (
                    "need",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="needs.need",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="offers.offer",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags_submitted",
                        to="communities.member",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flags_resolved",
                        to="communities.member",
                    ),
                ),
            ],
            options={
                "db_table": "moderation_flag",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["community", "status"],
                        name="moderation_comm_status_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("member__isnull", True),
                                ("need__isnull", False),
                                ("offer__isnull", True),
                            ),
                            models.Q(
                                ("member__isnull", True),
                                ("need__isnull", True),
                                ("offer__isnull", False),
                            ),
                            models.Q(
                                ("member__isnull", False),
                                ("need__isnull", True),
                                ("offer__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="moderation_flag_one_target",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("need__isnull", False), ("status", "open")),
                        fields=("reporter", "need"),
                        name="moderation_open_per_need",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("offer__isnull", False), ("status", "open")),
                        fields=("reporter", "offer"),
                        name="moderation_open_per_offer",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("member__isnull", False), ("status", "open")),
                        fields=("reporter", "member"),
                        name="moderation_open_per_member",
                    ),
                ],
            },
            bases=(apps.common.state.StateMachineMixin, models.Model),
        ),
    ]
