# Generated by Django 5.2.14 on 2026-07-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flag",
            name="target_type",
            field=models.CharField(
                choices=[("need", "Need"), ("offer", "Offer"), ("member", "Member"), ("page", "Page")], max_length=12
            ),
        ),
    ]
