# Generated by Django 5.2.14 on 2026-07-18 08:53

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0003_member_removed_at_member_removed_by"),
        ("moderation", "0002_alter_flag_target_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_received",
                        to="communities.member",
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="blocks_made", to="communities.member"
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="blocks", to="communities.community"
                    ),
                ),
            ],
            options={
                "db_table": "moderation_block",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["community", "blocker"], name="mod_block_blocker_idx"),
                    models.Index(fields=["community", "blocked"], name="mod_block_blocked_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("blocker", "blocked"), name="mod_block_unique_pair")],
            },
        ),
    ]
