# Generated by Django 5.2.14 on 2026-05-12 03:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Need",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "urgency",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("neighborhood", models.CharField(blank=True, max_length=100)),
                (
                    "contact_pref",
                    models.CharField(
                        choices=[("in_app", "In-app"), ("email", "Email"), ("phone", "Phone"), ("any", "Any")],
                        default="in_app",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("matched", "Matched"),
                            ("fulfilled", "Fulfilled"),
                            ("closed", "Closed"),
                            ("expired", "Expired"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("on_behalf_of", models.BinaryField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("custom", models.JSONField(blank=True, default=dict)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="communities.category")),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="needs", to="communities.community"
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="needs", to="communities.member"
                    ),
                ),
            ],
            options={
                "db_table": "needs_need",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["community", "status", "urgency"], name="needs_need_communi_fe29b2_idx"),
                    models.Index(fields=["expires_at"], name="needs_need_expires_a001a4_idx"),
                ],
            },
        ),
    ]
