# Generated by Django 5.2.14 on 2026-07-12 18:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('education', 'Education & tutoring'), ('legal', 'Legal aid'), ('health', 'Mental & physical health'), ('benefits', 'Benefits & financial help'), ('food', 'Food & essentials'), ('housing', 'Housing & shelter'), ('other', 'Other')], default='other', max_length=12)),
                ('title', models.CharField(max_length=120)),
                ('url', models.URLField(max_length=500)),
                ('blurb', models.CharField(blank=True, max_length=280)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resources_added', to='communities.member')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='communities.community')),
            ],
            options={
                'db_table': 'communities_resource',
                'ordering': ['category', 'sort_order', 'title'],
                'indexes': [models.Index(fields=['community', 'is_active'], name='comm_resource_active_idx')],
            },
        ),
    ]
