# Generated by Django 5.2.14 on 2026-07-18 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0002_resource_directory"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="communities.member",
            ),
        ),
    ]
