# Generated by Django 5.2.14 on 2026-09-30 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0003_member_removed_at_member_removed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("intake", "Intake helper"),
                    ("coordinator", "Coordinator"),
                    ("admin", "Admin"),
                ],
                default="member",
                max_length=15,
            ),
        ),
    ]
