# Generated by Django 5.2.14 on 2026-07-03 11:23

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.state


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FederationPeer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("base_url", models.URLField(blank=True, default="")),
                ("instance_id", models.CharField(max_length=64, unique=True)),
                ("jwk", models.JSONField(default=dict)),
                ("label", models.CharField(blank=True, default="", max_length=200)),
                ("locality", models.CharField(blank=True, default="", max_length=100)),
                ("capabilities", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("active", "Active"), ("blocked", "Blocked")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("pairing_salt", models.CharField(blank=True, default="", max_length=64)),
                ("pairing_hash", models.CharField(blank=True, default="", max_length=64)),
                ("pairing_expires_at", models.DateTimeField(blank=True, null=True)),
                ("requested_communities", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="federation_peers_approved",
                        to="communities.member",
                    ),
                ),
            ],
            options={
                "db_table": "federation_peer",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FederationLink",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("remote_community_uuid", models.UUIDField(blank=True, null=True)),
                ("remote_community_label", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("requested_by_us", models.BooleanField(default=False)),
                ("pairing_code_hash", models.CharField(blank=True, default="", max_length=64)),
                ("pairing_expires_at", models.DateTimeField(blank=True, null=True)),
                ("pairing_pepper", models.BinaryField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="federation_links_approved",
                        to="communities.member",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="federation_links",
                        to="communities.community",
                    ),
                ),
                (
                    "peer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="federation.federationpeer",
                    ),
                ),
            ],
            options={
                "db_table": "federation_link",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["community", "status"], name="federation__communi_be165b_idx")],
                "unique_together": {("peer", "community", "remote_community_uuid")},
            },
            bases=(apps.common.state.StateMachineMixin, models.Model),
        ),
    ]
