# Generated by Django 5.2.14 on 2026-07-03 17:07

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("consent", "0002_structured_grantee"),
        ("federation", "0001_initial"),
        ("needs", "0004_need_share_scope"),
        ("offers", "0002_offer_share_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="FederatedShare",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("remote_uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("receipt_jws", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("revoked", "Revoked"), ("expired", "Expired")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="federated_shares",
                        to="consent.consent",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="federation.federationlink",
                    ),
                ),
                (
                    "need",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="federated_shares",
                        to="needs.need",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="federated_shares",
                        to="offers.offer",
                    ),
                ),
            ],
            options={
                "db_table": "federation_share",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("need__isnull", False), ("offer__isnull", True)),
                            models.Q(("need__isnull", True), ("offer__isnull", False)),
                            _connector="OR",
                        ),
                        name="federated_share_exactly_one_record",
                    ),
                    models.UniqueConstraint(fields=("link", "need"), name="uniq_share_link_need"),
                    models.UniqueConstraint(fields=("link", "offer"), name="uniq_share_link_offer"),
                ],
            },
        ),
    ]
