# Generated by Django 5.2.14 on 2026-07-03 21:57

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0002_federatedshare"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShadowListing",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=8)),
                ("remote_uuid", models.UUIDField()),
                ("category", models.CharField(blank=True, default="", max_length=100)),
                ("urgency", models.CharField(blank=True, default="", max_length=10)),
                ("locality", models.CharField(blank=True, default="", max_length=100)),
                ("freshness", models.CharField(blank=True, default="", max_length=10)),
                ("radius_km", models.IntegerField(blank=True, null=True)),
                ("receipt_jws", models.TextField(blank=True, default="")),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shadows",
                        to="federation.federationlink",
                    ),
                ),
            ],
            options={
                "db_table": "federation_shadow",
                "ordering": ["-fetched_at"],
                "indexes": [models.Index(fields=["expires_at"], name="federation__expires_125412_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("link", "remote_uuid"), name="uniq_shadow_link_remote")
                ],
            },
        ),
    ]
