# Generated by Django 5.2.14 on 2026-07-03 23:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0003_shadowlisting"),
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FederatedMatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("role", models.CharField(choices=[("authority", "Authority"), ("mirror", "Mirror")], max_length=10)),
                ("proposal_uuid", models.UUIDField()),
                ("remote_match_uuid", models.UUIDField(blank=True, null=True)),
                ("contact_payload_enc", models.BinaryField(blank=True, null=True)),
                ("contact_payload_dek", models.BinaryField(blank=True, null=True)),
                ("contact_expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="federation.federationlink",
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="federated",
                        to="matches.match",
                    ),
                ),
            ],
            options={
                "db_table": "federation_match",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("link", "proposal_uuid"), name="uniq_fedmatch_link_proposal")
                ],
            },
        ),
    ]
