# Generated by Django 5.2.14 on 2026-07-05 10:18

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0004_federatedmatch"),
        ("offers", "0002_offer_share_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="federatedmatch",
            name="mirror_status",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
        migrations.AddField(
            model_name="federatedmatch",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="federated_matches",
                to="offers.offer",
            ),
        ),
        migrations.AddField(
            model_name="federatedmatch",
            name="remote_need_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="FederationEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("direction", models.CharField(choices=[("out", "Outbound"), ("in", "Inbound")], max_length=3)),
                ("event_uuid", models.UUIDField()),
                ("kind", models.CharField(max_length=32)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("payload_enc", models.BinaryField(blank=True, null=True)),
                ("payload_dek", models.BinaryField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("acked", "Acked"),
                            ("failed", "Failed"),
                            ("applied", "Applied"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="federation.federationlink",
                    ),
                ),
            ],
            options={
                "db_table": "federation_event",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["direction", "state", "next_attempt_at"], name="federation__directi_8ac464_idx"
                    )
                ],
                "constraints": [models.UniqueConstraint(fields=("link", "event_uuid"), name="uniq_fedevent_link_uuid")],
            },
        ),
    ]
