# Generated by Django 5.2.14 on 2026-07-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0004_federatedmatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="federationpeer",
            name="target_community_slug",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
