# Generated by Django 5.2.14 on 2026-07-06 03:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0005_federatedmatch_mirror_status_federatedmatch_offer_and_more"),
        ("federation", "0005_federationpeer_target_community_slug"),
    ]

    operations = []
