# Generated by Django 5.2.14 on 2026-07-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("federation", "0006_merge_20260705_2230"),
    ]

    operations = [
        migrations.AddField(
            model_name="federationlink",
            name="unreachable_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
