# Generated by Django 5.2.14 on 2026-07-27 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0003_member_removed_at_member_removed_by"),
        ("consent", "0002_structured_grantee"),
        ("people", "0004_person_name_bidx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consent",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consents_recorded",
                to="communities.member",
            ),
        ),
        migrations.AddField(
            model_name="consent",
            name="subject_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consents_about",
                to="people.person",
            ),
        ),
        migrations.AlterField(
            model_name="consent",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consents_given",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="consent",
            index=models.Index(fields=["subject_person"], name="consent_subject_person_idx"),
        ),
        migrations.AddConstraint(
            model_name="consent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("participant__isnull", False), ("subject_person__isnull", True)),
                    models.Q(("participant__isnull", True), ("subject_person__isnull", False)),
                    _connector="OR",
                ),
                name="consent_exactly_one_grantor",
            ),
        ),
    ]
