#!/usr/bin/env python3
"""Extract every UMI Protocol section citation (§N.N) from the codebase with context.

Feeds Slice 0 of the identity pipeline: the protocol spec is written FROM the reference
implementation, and its section numbers are FIXED so every existing citation resolves. This
script is the inventory of record — run it, commit its output, and build the spec skeleton
around the numbers it finds. It invents nothing; it only reports what the tree already cites.

Usage: python scripts/extract_citations.py > docs/protocol/citation-inventory.md
"""

from __future__ import annotations

import pathlib
import re
from collections import defaultdict

REPO = pathlib.Path(__file__).resolve().parent.parent
# The stale nested clone and third-party trees are not our citations.
SKIP = ("/.venv/", "/node_modules/", "/umi-exchange/umi-exchange/", "/.git/", "/staticfiles/")
EXER = (".py", ".html", ".md", ".txt", ".toml", ".cfg", ".json")
CITE = re.compile(r"§\s?(\d+(?:\.\d+)*)")


def wanted(path: pathlib.Path) -> bool:
    s = str(path)
    return path.suffix in EXER and not any(p in s for p in SKIP)


def section_sort_key(sec: str) -> tuple[int, ...]:
    return tuple(int(p) for p in sec.split("."))


def main() -> None:
    hits: dict[str, list[tuple[str, int, str]]] = defaultdict(list)
    for path in REPO.rglob("*"):
        if not path.is_file() or not wanted(path):
            continue
        try:
            lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue
        rel = path.relative_to(REPO)
        for n, line in enumerate(lines, 1):
            for m in CITE.finditer(line):
                hits[m.group(1)].append((str(rel), n, line.strip()[:160]))

    sections = sorted(hits, key=section_sort_key)
    total = sum(len(v) for v in hits.values())

    print("# UMI Protocol v0.1 — citation inventory")
    print()
    print("> Auto-generated by `scripts/extract_citations.py`. The section numbers below are the")
    print("> FIXED skeleton of the spec: every citation in the reference implementation must")
    print("> resolve to one of them. Do not renumber. Regenerate after any change that adds a")
    print("> citation; the count is a tripwire.")
    print()
    print(f"**{len(sections)} distinct sections, {total} total citations.**")
    print()
    print("| § | count | first evidence |")
    print("|---|---|---|")
    for sec in sections:
        refs = hits[sec]
        first = refs[0]
        print(f"| §{sec} | {len(refs)} | `{first[0]}:{first[1]}` |")

    print()
    print("## Full evidence, by section")
    for sec in sections:
        print()
        print(f"### §{sec} ({len(hits[sec])})")
        for rel, n, text in hits[sec]:
            print(f"- `{rel}:{n}` — {text}")


if __name__ == "__main__":
    main()
