#!/usr/bin/env python
"""Pre-render docs/protocol/spec.md into the committed /protocol/ fragment (pipeline §B1).

Build-time only — the server never renders markdown at request time (that's the point:
the page stays true with zero runtime dependencies). Run after ANY edit to spec.md:

    .venv/bin/python scripts/render_protocol.py

The staleness test (tests/test_protocol.py) hashes spec.md against the hash stamped in
the fragment, so a forgotten rerun fails the suite instead of shipping a stale floor.
"""

import hashlib
import re
import sys
from pathlib import Path

import markdown
import nh3

REPO_ROOT = Path(__file__).resolve().parent.parent
SPEC = REPO_ROOT / "docs" / "protocol" / "spec.md"
FRAGMENT = REPO_ROOT / "templates" / "pages" / "_protocol_spec.html"

# The fragment is our own keyed document, but it still goes through nh3 so the ONLY
# |safe surface in the app stays nh3-written — same posture as Layer C (§G).
ALLOWED_TAGS = {
    "h1",
    "h2",
    "h3",
    "h4",
    "p",
    "br",
    "em",
    "strong",
    "ul",
    "ol",
    "li",
    "blockquote",
    "a",
    "code",
    "pre",
    "hr",
    "table",
    "thead",
    "tbody",
    "tr",
    "th",
    "td",
}
ALLOWED_ATTRS = {
    "a": {"href", "title"},
    "h1": {"id"},
    "h2": {"id"},
    "h3": {"id"},
    "h4": {"id"},
}


def spec_slugify(value: str, separator: str) -> str:
    """Match the spec's own hand-written anchors (e.g. `#13--conformance`): drop `§`,
    strip punctuation, then turn EVERY space into the separator without collapsing —
    so the spaces around an em-dash become a double hyphen, as the author wrote them."""
    value = value.replace("§", "")
    value = re.sub(r"[^\w\s-]", "", value).strip().lower()
    return re.sub(r"\s", separator, value)


def main() -> int:
    source = SPEC.read_bytes()
    md = markdown.Markdown(
        extensions=["toc", "tables", "sane_lists"],
        extension_configs={
            "toc": {"toc_depth": "2-2", "slugify": spec_slugify},  # h2 §-sections; h1 is the title
        },
    )
    body = md.convert(source.decode("utf-8"))

    clean_body = nh3.clean(
        body,
        tags=ALLOWED_TAGS,
        attributes=ALLOWED_ATTRS,
        url_schemes={"https", "http", "mailto"},
        link_rel="noopener",
    )
    clean_toc = nh3.clean(
        md.toc,
        tags={"ul", "li", "a"},
        attributes={"a": {"href"}},
        url_schemes=set(),
        link_rel=None,
    )

    # Keyed reading order (wireframe 01): document head (h1, version, license, status),
    # then the intro block the template adds, then the TOC, then the sections. The view
    # splits on the markers so the template can interleave its intro card.
    first_h2 = clean_body.index("<h2")
    head, sections = clean_body[:first_h2], clean_body[first_h2:]

    digest = hashlib.sha256(source).hexdigest()
    FRAGMENT.write_text(
        f"<!-- spec-sha256:{digest} — generated by scripts/render_protocol.py; do not hand-edit -->\n"
        f'<article id="protocol-head">\n{head}\n</article>\n'
        "<!--SPLIT-->\n"
        f'<nav id="protocol-toc" aria-label="Sections of the protocol">\n{clean_toc}\n</nav>\n'
        "<!--SPLIT-->\n"
        f'<article id="protocol-article">\n{sections}\n</article>\n'
    )
    print(f"wrote {FRAGMENT.relative_to(REPO_ROOT)} (spec sha256 {digest[:12]}…)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
