# Generated by Django 5.2.14 on 2026-07-16 17:41

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.common.state


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("communities", "0002_resource_directory"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityPage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published"), ("archived", "Archived")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("content_md", models.TextField(blank=True)),
                ("content_html", models.TextField(blank=True, editable=False)),
                ("show_on_landing", models.BooleanField(default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("moderation_hidden", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("first_published_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pages", to="communities.community"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pages_created",
                        to="communities.member",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages_published",
                        to="communities.member",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pages_updated",
                        to="communities.member",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "title"],
                "indexes": [
                    models.Index(
                        fields=["community", "status", "show_on_landing"], name="pages_commu_communi_6f5c47_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "archived"), _negated=True),
                        fields=("community", "slug"),
                        name="uniq_live_page_slug_per_community",
                    )
                ],
            },
            bases=(apps.common.state.StateMachineMixin, models.Model),
        ),
    ]
