# Generated by Django 5.2.14 on 2026-06-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("casework", "0004_envelope_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="casenote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
