# Generated by Django 5.2.14 on 2026-07-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casework', '0007_drop_emergency_justification_plaintext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casefile',
            name='sensitivity',
            field=models.CharField(choices=[('standard', 'Standard'), ('restricted', 'Restricted')], default='restricted', max_length=12),
        ),
    ]
