# Generated by Django 5.2.16 on 2026-07-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("match_proposed", "Match Proposed"),
                    ("match_accepted", "Match Accepted"),
                    ("match_fulfilled", "Match Fulfilled"),
                    ("match_cancelled", "Match Cancelled"),
                    ("need_expiring", "Need Expiring"),
                    ("need_expired", "Need Expired"),
                    ("flag_submitted", "Content Reported"),
                ],
                max_length=30,
            ),
        ),
    ]
