# Generated by Django 5.2.14 on 2026-05-12 03:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        ('needs', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('fulfilled', 'Fulfilled'), ('unfulfilled', 'Unfulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='proposed', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('proposed_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('custom', models.JSONField(blank=True, default=dict)),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='needs.need')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='offers.offer')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_matches', to='communities.member')),
            ],
            options={
                'db_table': 'matches_match',
                'ordering': ['-proposed_at'],
            },
        ),
    ]
