# Generated by Django 5.2.14 on 2026-10-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="asker_yes_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="helper_yes_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
